[package]
name = "destinecarma/draggable"
description = "Allows you to make your GuiObjects Draggable"
version = "1.1.3"
license = "MIT"
authors = ["DestinEcarma"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "lucasmzreal/fastsignal@10.2.1"