title = "Draggable"                                      # From Git
gitRepoUrl = "https://github.com/DestinEcarma/draggable" # From Git

classOrder = ["Draggable"]

[home]
enabled = true
includeReadme = false

[docusaurus]
projectName = "Draggable"
baseUrl = "/draggable"
tagline = "Effortlessly replace the deprecated Draggable property in GuiObjects"
