[package]
name = "makerdoe/draggable"
description = "Allows you to make your GuiObjects Draggable"
version = "1.1.0"
license = "MIT"
authors = ["MakerDoe"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "lucasmzreal/fastsignal@10.2.1"